# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adoweather-service
  namespace: adoweather-namespace
spec:
  type: LoadBalancer
  selector:
    app: adoweather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
